import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-blue-950 text-white shadow-md">
          <div className="mx-auto flex max-w-5xl items-center gap-8 px-4 py-3">
            <Link
              href="/"
              className="text-sm font-medium text-white/90 transition hover:text-white"
            >
              Home
            </Link>
            <Link
              href="/leagues"
              className="text-sm font-medium text-white/90 transition hover:text-white"
            >
              Leghe
            </Link>
            <Link
              href="/trade"
              className="text-sm font-medium text-white/90 transition hover:text-white"
            >
              Trading
            </Link>
            <Link
              href="/account"
              className="text-sm font-medium text-white/90 transition hover:text-white"
            >
              Account
            </Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
